// SPDX-License-Identifier: AGPL-3.0-only
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace ArcForges.Web.Tooling.Candidate;

/// <summary>
/// The rules shared by the candidate build and its verifier: the reviewed inputs, the pinned Worker, the legal and notice
/// files, the build SBOM and the sealed manifest. Every value here is derived from the repository or the Site source; no
/// timestamp or machine path is an input, so two builds of the same inputs are the same bytes.
/// </summary>
internal static class CandidateCore
{
    /// <summary>The manifest schema, the same as the React candidate's.</summary>
    public const int ManifestSchema = 1;

    /// <summary>The sealed manifest path (not listed in its own file map).</summary>
    public const string ManifestPath = "manifest.json";

    /// <summary>The provenance receipt path (listed in the manifest, but its own members exclude it).</summary>
    public const string ReceiptPath = "provenance/receipt.json";

    /// <summary>The emitted canonical-host Worker (the JavaScript form of worker/index.ts).</summary>
    public const string WorkerPath = "worker/index.js";

    /// <summary>The candidate wrangler configuration.</summary>
    public const string WranglerPath = "wrangler.json";

    /// <summary>The build SBOM and the runtime SBOM of the public Site.</summary>
    public const string SbomPath = "sbom.cdx.json";

    /// <summary>The runtime SBOM path.</summary>
    public const string RuntimeSbomPath = "runtime-sbom.cdx.json";

    /// <summary>The static public assets are published under this prefix (the wrangler assets directory).</summary>
    public const string AssetsPrefix = "assets/";

    /// <summary>The full AGPL text, published as the licence file.</summary>
    public const string LicencePath = "LICENSE";

    /// <summary>The source provenance notice, published beside the licence.</summary>
    public const string SourceNoticePath = "eng/provenance/NOTICE.txt";

    /// <summary>The reviewed dependency policy, bound into the receipt.</summary>
    public const string PolicyPath = "eng/policy/dependency-policy.json";

    /// <summary>The Tailwind preflight licence text: the public stylesheet derives from Tailwind preflight.</summary>
    public const string TailwindLicencePath = "third-party/tailwind.LICENSE.txt";

    /// <summary>The per-project lock files of the Site closure, read for the build SBOM.</summary>
    public static readonly string[] SiteLockPaths =
    [
        "src/ArcForges.Web.Site/packages.lock.json",
        "src/ArcForges.Web.Ui/packages.lock.json",
    ];

    /// <summary>
    /// The SHA-256 of the Worker JavaScript emitted from worker/index.ts by Node type stripping (LF-normalised). The Node
    /// emitter (tooling/candidate.ts) and this pin must agree; a changed Worker source needs a reviewed change to this value.
    /// </summary>
    public const string WorkerSha256 = "5020b1504e965aa428bb3bcca2bd270bfd5e4adb53dbe8fb0d3338bca401d088";

    /// <summary>The public pages every candidate must publish (the React candidate's required pages).</summary>
    public static readonly string[] RequiredPages = ["index.html", "hello/index.html", "cloud-hello/index.html", "404.html"];

    /// <summary>The files that are not generated by the Site and that every candidate publishes beside it.</summary>
    public static readonly string[] IdentityAndLegalFiles =
    [
        "license.txt",
        "third-party-notices.txt",
        "source-provenance.txt",
        "__build.json",
        "__build-info.json",
    ];

    /// <summary>The members every candidate must hold, as candidate paths.</summary>
    public static IReadOnlyList<string> RequiredMembers { get; } =
    [
        .. RequiredPages.Select(page => AssetsPrefix + page),
        AssetsPrefix + "_headers",
        .. IdentityAndLegalFiles.Select(file => AssetsPrefix + file),
        SbomPath,
        RuntimeSbomPath,
        WranglerPath,
        WorkerPath,
        ReceiptPath,
    ];

    private static readonly UTF8Encoding StrictUtf8 = new(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true);
    private static readonly JsonSerializerOptions Indented = new() { WriteIndented = true };

    /// <summary>The lower-case hexadecimal SHA-256 of the bytes.</summary>
    public static string Sha256(ReadOnlySpan<byte> bytes) => Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();

    /// <summary>Decodes strict UTF-8 and normalises CRLF to LF, the bytes a browser or Node text reader sees.</summary>
    public static byte[] Lf(ReadOnlySpan<byte> bytes) =>
        Encoding.UTF8.GetBytes(StrictUtf8.GetString(bytes).Replace("\r\n", "\n", StringComparison.Ordinal));

    /// <summary>Serialises a JSON document with two-space indentation and one trailing line feed.</summary>
    public static byte[] Json(JsonNode node) =>
        Encoding.UTF8.GetBytes(JsonSerializer.Serialize(node, Indented) + "\n");

    /// <summary>Reads one repository file. The path is a fixed constant of this tool, never user input.</summary>
    public static byte[] ReadRepo(string repository, string relativePath)
    {
        var path = Path.Combine(repository, relativePath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(path))
            throw new InvalidOperationException("Missing reviewed repository input: " + relativePath);
        return File.ReadAllBytes(path);
    }

    /// <summary>Reads every regular file under a directory as relative '/' paths. Links and reparse points are refused.</summary>
    public static SortedDictionary<string, byte[]> ReadTree(string directory)
    {
        var files = new SortedDictionary<string, byte[]>(StringComparer.Ordinal);
        var root = Path.GetFullPath(directory);
        void Visit(string current)
        {
            foreach (var entry in Directory.EnumerateFileSystemEntries(current))
            {
                var attributes = File.GetAttributes(entry);
                if ((attributes & FileAttributes.ReparsePoint) != 0)
                    throw new InvalidOperationException("Links are not allowed in a candidate: " + entry);
                if ((attributes & FileAttributes.Directory) != 0)
                {
                    Visit(entry);
                    continue;
                }
                var relative = Path.GetRelativePath(root, entry).Replace(Path.DirectorySeparatorChar, '/');
                files[relative] = File.ReadAllBytes(entry);
            }
        }
        Visit(root);
        return files;
    }

    /// <summary>
    /// The published third-party notices. The static Site ships only Tailwind preflight-derived CSS from third-party
    /// material, so the notice text covers exactly that licence; a change to the shipped third-party content changes it.
    /// </summary>
    public static byte[] Notices(string repository)
    {
        var tailwind = Lf(ReadRepo(repository, TailwindLicencePath));
        var text = new StringBuilder();
        text.Append("ArcForges Web third-party notices\n");
        text.Append("Generated for the C# static Site candidate. The public Site publishes no JavaScript and no runtime\n");
        text.Append("dependency. Its stylesheet derives from Tailwind preflight (MIT); every other published file is first-party.\n");
        text.Append("\n===== Tailwind CSS preflight (MIT) =====\n");
        text.Append(Encoding.UTF8.GetString(tailwind));
        return Encoding.UTF8.GetBytes(text.ToString());
    }

    /// <summary>The published licence file: the full AGPL text with LF line endings.</summary>
    public static byte[] Licence(string repository) => Lf(ReadRepo(repository, LicencePath));

    /// <summary>The published source provenance notice with LF line endings.</summary>
    public static byte[] SourceNotice(string repository) => Lf(ReadRepo(repository, SourceNoticePath));

    /// <summary>The build identity: the candidate's <c>__build.json</c>, which the deploy identity poll reads.</summary>
    public static byte[] BuildJson(string version, string source) =>
        Json(new JsonObject { ["version"] = version, ["source"] = source });

    /// <summary>
    /// The build SBOM of the public Site: every non-project NuGet package of the Site and Ui locks, with its exact
    /// version, its content hash and the licence the reviewed closure records for it. A package with no reviewed licence
    /// fails the build.
    /// </summary>
    public static byte[] BuildSbom(string repository)
    {
        var closure = ReviewedLicences(repository);
        var components = new SortedDictionary<string, JsonObject>(StringComparer.Ordinal);
        foreach (var lockPath in SiteLockPaths)
        {
            var document = JsonNode.Parse(ReadRepo(repository, lockPath))?.AsObject()
                ?? throw new InvalidOperationException("Invalid lock file: " + lockPath);
            var frameworks = document["dependencies"]?.AsObject()
                ?? throw new InvalidOperationException("A lock file without dependencies: " + lockPath);
            foreach (var (_, dependencies) in frameworks)
            {
                foreach (var (name, value) in dependencies!.AsObject())
                {
                    var entry = value!.AsObject();
                    if (entry["type"]?.GetValue<string>() == "Project")
                        continue;
                    var version = entry["resolved"]?.GetValue<string>()
                        ?? throw new InvalidOperationException("A package without a resolved version: " + name);
                    var contentHash = entry["contentHash"]?.GetValue<string>()
                        ?? throw new InvalidOperationException("A package without a content hash: " + name);
                    var purl = $"pkg:nuget/{name}@{version}";
                    if (components.ContainsKey(purl))
                        continue;
                    var licenceKey = (name + "/" + version).ToLowerInvariant();
                    if (!closure.TryGetValue(licenceKey, out var licence))
                        throw new InvalidOperationException("No reviewed licence for " + purl);
                    components[purl] = new JsonObject
                    {
                        ["type"] = "library",
                        ["bom-ref"] = purl,
                        ["name"] = name,
                        ["version"] = version,
                        ["purl"] = purl,
                        ["licenses"] = new JsonArray(new JsonObject { ["license"] = new JsonObject { ["id"] = licence } }),
                        ["hashes"] = new JsonArray(new JsonObject
                        {
                            ["alg"] = "SHA-512",
                            ["content"] = Convert.ToHexString(Convert.FromBase64String(contentHash)).ToLowerInvariant(),
                        }),
                    };
                }
            }
        }
        var bom = new JsonObject
        {
            ["bomFormat"] = "CycloneDX",
            ["specVersion"] = "1.5",
            ["version"] = 1,
            ["metadata"] = new JsonObject
            {
                ["component"] = new JsonObject { ["type"] = "application", ["name"] = "arcforges-web-site", ["bom-ref"] = "arcforges-web-site" },
            },
            ["components"] = new JsonArray(components.Values.Select(component => (JsonNode)component).ToArray()),
        };
        return Json(bom);
    }

    /// <summary>The runtime SBOM: the static Site ships no runtime dependency, so its component list is empty.</summary>
    public static byte[] RuntimeSbom() =>
        Json(new JsonObject
        {
            ["bomFormat"] = "CycloneDX",
            ["specVersion"] = "1.5",
            ["version"] = 1,
            ["components"] = new JsonArray(),
        });

    /// <summary>The candidate wrangler configuration: the reviewed root configuration with the candidate's assets directory.</summary>
    public static JsonObject CandidateWrangler(string repository)
    {
        var root = JsonNode.Parse(ReadRepo(repository, WranglerPath))?.AsObject()
            ?? throw new InvalidOperationException("Invalid wrangler.json");
        root.Remove("$schema");
        var assets = root["assets"]?.AsObject()
            ?? throw new InvalidOperationException("wrangler.json has no assets section");
        assets["directory"] = "./assets";
        return root;
    }

    /// <summary>The provenance receipt: the source, the version, the reviewed policy digest and every member's digest.</summary>
    public static byte[] Receipt(string source, string version, string policySha256, IReadOnlyDictionary<string, byte[]> members)
    {
        var listed = new JsonObject();
        foreach (var (path, bytes) in members.OrderBy(pair => pair.Key, StringComparer.Ordinal))
            if (path != ManifestPath && path != ReceiptPath)
                listed[path] = Sha256(bytes);
        return Json(new JsonObject
        {
            ["schemaVersion"] = 1,
            ["repository"] = "Web",
            ["source"] = source,
            ["version"] = version,
            ["policySha256"] = policySha256,
            ["members"] = listed,
        });
    }

    /// <summary>The reviewed dependency policy digest, LF-normalised, that the receipt binds.</summary>
    public static string PolicySha256(string repository) => Sha256(Lf(ReadRepo(repository, PolicyPath)));

    /// <summary>The Worker digest check: the emitted script must be exactly the pinned bytes.</summary>
    public static void RequireWorker(ReadOnlySpan<byte> bytes)
    {
        if (Sha256(bytes) != WorkerSha256)
            throw new InvalidOperationException("Worker script changed from the reviewed source (worker/index.ts).");
    }

    /// <summary>The licence key to SPDX licence map of the reviewed NuGet closure.</summary>
    private static Dictionary<string, string> ReviewedLicences(string repository)
    {
        var policy = JsonNode.Parse(ReadRepo(repository, PolicyPath))?.AsObject()
            ?? throw new InvalidOperationException("Invalid dependency policy");
        var closure = policy["nugetClosure"]?.AsObject()
            ?? throw new InvalidOperationException("The dependency policy has no nugetClosure");
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var (key, value) in closure)
            result[key.ToLowerInvariant()] = value!["licence"]?.GetValue<string>()
                ?? throw new InvalidOperationException("No licence for " + key);
        return result;
    }
}
