<Project Sdk="Microsoft.NET.Sdk.Razor">
  <!-- SPDX-License-Identifier: AGPL-3.0-only -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ArcForges.Web.Ui/ArcForges.Web.Ui.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets/**" />
  </ItemGroup>
  <PropertyGroup>
    <LicenceBoundary>AGPL</LicenceBoundary>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
</Project>
