<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <!-- SPDX-License-Identifier: AGPL-3.0-only -->
  <PropertyGroup>
    <RunAOTCompilation>false</RunAOTCompilation>
    <DisableTransitiveFrameworkReferences>true</DisableTransitiveFrameworkReferences>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ArcForges.Web.Ui/ArcForges.Web.Ui.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <LicenceBoundary>AGPL</LicenceBoundary>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
</Project>
