<Project Sdk="Microsoft.NET.Sdk">
  <!-- SPDX-License-Identifier: AGPL-3.0-only -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <ProjectReference Include="../../tools/ArcForges.Web.Tooling/ArcForges.Web.Tooling.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <LicenceBoundary>AGPL</LicenceBoundary>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
</Project>
